### ISSUE TITLE
Cannot abort operation while running

### ISSUE THREAD

**Issue by Mhowser** [DaMatrix/bedrock#1]
When the program is running, the start button should should display as Stop to end the program, but not close it.

**Comment by DaMatrix** [comment]
Implemented as of 046c119810fcb2b290103d5f9c14fbdb038fd6dc , will make a new release now

**Comment by DaMatrix** [comment]
Implemented in 046c119810fcb2b290103d5f9c14fbdb038fd6dc , will make a new release now.
