### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by tycrek** [DaMatrix/bedrock#3]
Sorry accidentally posted before commenting.

Can there be docs on building and usage? I'm confused as to the three checkbox states (check, empty, square).

Other than that it seems good, running at 282 million chunks per second on an i7-9850H.

**Comment by DaMatrix** [comment]
sure, i've been meaning to add some documentation at some point.

compilation is just like any other maven project: execute `mvn package` in the root directory, the compiled jar will be in the `target` directory (choose the one that isn't prefixed with `original-`).

as to the checkbox states:
- empty: there is no bedrock at the given location
- check: there is bedrock at the given location
- square: wildcard, matches both bedrock and not-bedrock
one of my plans is to make the checkboxes textured, which should hopefully clear up some confusion (i get asked that question a lot :P)

**Comment by tycrek** [comment]
Awesome, I got it to build pretty quick. I might make a PR with some basic info in the README.md, you can change it if you want.
